# Explore Embeddings

Query and inspect the embeddings table.

In [1]:
import duckdb

conn = duckdb.connect("../data/jt3.duckdb", read_only=True)

%load_ext sql
%sql conn --alias duckdb

The 'toml' package isn't installed. To load settings from pyproject.toml or ~/.jupysql/config, install with: pip install toml

In [2]:
%%sql
SELECT * FROM embeddings

Running query in 'duckdb'

+---------+-------------+----------------+---------+------------------+------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
| game_id | round_index | category_index | clue_id |      field       |                                                         source_text                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  embedding                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |        model_name        |
+---------+-------------+----------------+---------+------------------+------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------+
|   9263  |      0      |       0        |  J_1_1  |       text       |                          It's something of little importance or value, like, say, legumes in a heap                          |  [-0.17446370422840118, -0.016353318467736244, -0.39731553196907043, -0.11986353248357773, 0.09433507174253464, 0.021380707621574402, 0.1282733827829361, -0.0880516767501831, -0.0895010456442833, -0.017023703083395958, 0.07120338827371597, -0.022531552240252495, -0.05468852445483208, -0.17166325449943542, 0.19621537625789642, 0.06225461885333061, -0.042154036462306976, -0.25734132528305054, -0.11980117112398148, -0.2837127447128296, 0.06656967103481293, -0.07208779454231262, 0.1650538295507431, -0.015432856976985931, 0.08172721415758133, 0.054955098778009415, 0.15582016110420227, -0.09935598820447922, -0.06335864216089249, 0.06934107840061188, -0.057256825268268585, -0.07106459140777588, -0.14271746575832367, 0.009536601603031158, -0.09080442041158676, -0.016341911628842354, 0.03166063129901886, 0.18029239773750305, 0.016292111948132515, 0.14899161458015442, -0.06379386782646179, 0.02654433809220791, 0.13562221825122833, -0.07209168374538422, 0.018266642466187477, -0.25746557116508484, 0.005079488269984722, 0.05194908753037453, -0.1827041655778885, 0.3330705761909485, 0.00917042512446642, -0.025918547064065933, -0.01771497167646885, -0.07095693796873093, -0.07610414922237396, -0.045656219124794006, -0.06824138760566711, -0.07598854601383209, 0.0754869133234024, 0.07112789899110794, 0.056890763342380524, 0.10875319689512253, 0.14516590535640717, 0.12472182512283325] | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_1  | correct_response |                                                       a hill of beans                                                        |           [0.1540491133928299, 0.022865740582346916, 0.18429936468601227, 0.05346277728676796, 0.053099777549505234, -0.07936746627092361, 0.03762352094054222, -0.3206427991390228, 0.2246781885623932, -0.2422379106283188, 0.15120378136634827, 0.1074499562382698, 0.12685173749923706, -0.04432673007249832, -0.04852211847901344, 0.11707521229982376, -0.15489360690116882, -0.22555135190486908, 0.07664107531309128, -0.13576474785804749, 0.17491689324378967, -0.07623708248138428, -0.016345128417015076, -0.16257572174072266, 0.09404119104146957, 0.003218847792595625, 0.07758336514234543, 0.030723348259925842, -0.10088455677032471, -0.12254799902439117, 0.03053584322333336, 0.0674009770154953, 0.0952313095331192, -0.08667473495006561, -0.10239531099796295, 0.2824532091617584, 0.11309589445590973, 0.015262351371347904, -0.1257714480161667, 0.22780358791351318, -0.04576869681477547, 0.033060651272535324, 0.036269351840019226, 0.16916947066783905, 0.05897041782736778, 0.023093173280358315, 0.19091594219207764, 0.03431461378931999, 0.04384084790945053, 0.22283276915550232, 0.17427155375480652, -0.09468912333250046, 0.009598148055374622, -0.03952210023999214, 0.07263816148042679, 0.1334330141544342, 0.05684087052941322, 0.2061878740787506, 0.06821886450052261, -0.08421845734119415, 0.008259473368525505, 0.03927087038755417, -0.005258851684629917, -0.04479589685797691]           | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_2  |       text       |   In a 1785 poem William Cowper referred to this as "the very spice of life"; spoken like a man who's never tried sriracha   |          [-0.1616188883781433, -0.2529253661632538, -0.1587630808353424, 0.37399816513061523, 0.24604849517345428, 0.17043064534664154, -0.028401266783475876, 0.039034318178892136, -0.024851109832525253, 0.01651669666171074, 0.09880105406045914, 0.15945926308631897, -0.09501028805971146, 0.3628653585910797, 0.052471596747636795, 0.0067405072040855885, -0.11479046195745468, -0.06072898581624031, -0.006933484226465225, 0.07337366789579391, 0.16144968569278717, 0.06047087907791138, -0.046560149639844894, 0.169076606631279, -0.01935535855591297, 0.18489834666252136, -0.04225568845868111, 0.01689773239195347, 0.09828576445579529, 0.004219702910631895, 0.08135221898555756, 0.09833607822656631, -0.06070603430271149, -0.1288834512233734, -0.1878904104232788, -0.08063667267560959, 0.13578437268733978, 0.056744422763586044, 0.04786762595176697, 0.059116821736097336, -0.03819803148508072, -0.1643294394016266, -0.18940579891204834, 0.03863772749900818, 0.10736031085252762, 0.12177786231040955, -0.07551693916320801, -0.005861799698323011, 0.031805407255887985, 0.00987228937447071, 0.04869591072201729, 0.11572060734033585, -0.031217185780405998, 0.058552343398332596, 0.0730411559343338, 0.09913354367017746, 0.06586422026157379, 0.0939895436167717, 0.23587566614151, -0.013313970528542995, 0.01494687981903553, -0.0726928636431694, -0.023058727383613586, 0.1703815460205078]         | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_2  | correct_response |                                                           variety                                                            |  [0.20061267912387848, 0.13144297897815704, -0.030075879767537117, -0.25808706879615784, -0.2859693467617035, -0.03177608549594879, -0.21725969016551971, -0.5064992904663086, 0.114284448325634, -0.11642114073038101, 0.07891422510147095, 0.06353531032800674, 0.0017672792309895158, 0.003054617205634713, 0.08837386965751648, -0.08680301904678345, -0.040095001459121704, 0.01874639093875885, 0.08114911615848541, -0.08263690769672394, -0.18297399580478668, 0.012265275232493877, -0.0051524024456739426, -0.048237789422273636, -0.1095060408115387, -0.11313001066446304, -0.1361718475818634, -0.04604065790772438, 0.009687494486570358, -0.16910280287265778, -0.047622255980968475, -6.16195538896136e-05, -0.08895162492990494, -0.18106240034103394, -0.08460882306098938, 0.13931773602962494, 0.06806294620037079, 0.009987222962081432, 0.20286209881305695, -0.059890326112508774, 0.04036879166960716, 0.009899642318487167, 0.13719962537288666, -0.05379146710038185, 0.10209566354751587, 0.012087518349289894, 0.056985605508089066, 0.03088177740573883, 0.11942232400178909, 0.15694135427474976, 0.11753257364034653, 0.17917802929878235, 0.12129883468151093, -0.004049617797136307, 0.020006850361824036, 0.06390772759914398, 0.13120514154434204, 0.09052205830812454, -0.09451134502887726, 0.08000101149082184, 0.04020775854587555, -0.07352090626955032, -0.02813783288002014, 0.02995622344315052] | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_3  |       text       |                At the dinner table, it can be a tempting item, perhaps twice baked--or a subject best avoided                | [-0.4115370512008667, 0.17650440335273743, -0.054460491985082626, 0.12092040479183197, -0.26295241713523865, 0.04496373236179352, -0.1917961686849594, -0.2088060826063156, 0.023133806884288788, -0.048040419816970825, 0.06849146634340286, -0.04507245123386383, 0.06876523792743683, -0.04462924227118492, 0.24012748897075653, -0.21152974665164948, -0.05641425400972366, -0.002346412045881152, 0.03903678059577942, -0.18272903561592102, -0.07183527946472168, 0.10971080511808395, -0.05819600820541382, 0.04963863641023636, 0.07384657114744186, 0.06479906290769577, -0.020350290462374687, -0.029805922880768776, -0.06422886997461319, 0.10420610755681992, -0.15536512434482574, -0.007617585826665163, 0.0931391566991806, -0.08357654511928558, 0.05751539021730423, 0.301309198141098, 0.18524344265460968, -0.16539901494979858, 0.04447060823440552, 0.15609188377857208, 0.07707928866147995, -0.15513896942138672, 0.15520475804805756, -0.022152919322252274, 0.07881377637386322, -0.029810741543769836, 0.021180985495448112, -0.23395922780036926, -0.07763615995645523, 0.11221268773078918, 0.018344325944781303, 0.07658889889717102, 0.015689002349972725, 0.08476444333791733, -0.009734123013913631, -0.0010554054751992226, 0.12236668169498444, -0.08545007556676865, 0.08671493828296661, -0.05029086023569107, -0.014450108632445335, 0.011387426406145096, -0.1371239870786667, -0.04370059072971344] | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_3  | correct_response |                                                         a hot potato                                                         |     [-0.031173907220363617, -0.24894849956035614, -1.5961810277076438e-05, -0.10812616348266602, 0.011405431665480137, 0.016674894839525223, 0.08850650489330292, -0.25143933296203613, -0.07770531624555588, -0.02455591782927513, -0.056739650666713715, 0.03518862649798393, 0.25628000497817993, -0.15247584879398346, 0.15742747485637665, -0.1352129578590393, 0.06065388768911362, 0.1524956226348877, -0.135106161236763, -0.10371468216180801, -0.0741368755698204, -0.12225505709648132, 0.3035765588283539, -0.009642858058214188, -0.1521221548318863, -0.06771215051412582, -0.15985454618930817, 0.05504227429628372, 0.14266155660152435, 0.19018147885799408, 0.09853900969028473, -0.027628092095255852, 0.10736814886331558, -0.06312999874353409, -0.10928952693939209, 0.10721052438020706, 0.17196889221668243, 0.21863795816898346, 0.032347891479730606, 0.20034898817539215, 0.14735567569732666, -0.07307034730911255, -0.016644461080431938, -0.026822851970791817, 0.08200004696846008, -0.08809792250394821, 0.0974329486489296, -0.14189249277114868, -0.12401849776506424, -0.0070733195170760155, -0.15925972163677216, 0.16120219230651855, 0.04351227357983589, 0.024534765630960464, 0.2676408886909485, 0.10003001987934113, -0.06824174523353577, 0.06263052672147751, 0.12243864685297012, 0.02423863485455513, -0.0789637640118599, 0.06725645065307617, 0.04022519290447235, 0.04170932620763779]    | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_4  |       text       |          TV's "MythBusters" once tested whether "taking" this is "as easy" as the idiom suggests--conclusion: nope           |    [-0.37128251791000366, 0.15296967327594757, -0.2968848943710327, -0.1934562474489212, 0.2689562439918518, -0.043937552720308304, -0.24363091588020325, -0.11361679434776306, -0.033825356513261795, 0.11843480914831161, -0.07893422991037369, 0.007872591726481915, -0.2034459263086319, 0.0022514527663588524, 0.1172931045293808, 0.1286669373512268, -0.13182903826236725, -0.03891592472791672, 0.1136000007390976, -0.16285642981529236, 0.1586034595966339, 0.24315586686134338, -0.011656474322080612, -0.19232498109340668, -0.022835638374090195, 0.013341162353754044, -0.02913961000740528, 0.03583123907446861, -0.0416019968688488, 0.024013983085751534, 0.00950491800904274, -0.06372740864753723, -0.07266916334629059, 0.001953497529029846, -0.02714172564446926, 0.004984481260180473, 0.16146066784858704, 0.03626355156302452, -0.051089297980070114, 0.07810565829277039, -0.1263594627380371, -0.07004256546497345, -0.032100897282361984, 0.12659716606140137, 0.055825769901275635, 0.1693679839372635, 0.13573560118675232, 0.08309603482484818, 0.08893002569675446, 0.00984723586589098, -0.045790139585733414, -0.06042461097240448, -0.059428319334983826, 0.08229611068964005, 0.2077547162771225, 0.03702092543244362, -0.024049634113907814, 0.035270482301712036, 0.14030514657497406, 0.029784878715872765, -0.07456623017787933, -0.1553654819726944, 0.14680413901805878, -0.07088504731655121]    | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_4  | correct_response |                                                    take candy from a baby                                                    |     [-0.05053276941180229, -0.19897708296775818, 0.12436041235923767, -0.1475996971130371, -0.22153131663799286, 0.1330125331878662, -0.16304650902748108, -0.23380492627620697, 0.061581674963235855, -0.1322551667690277, 0.07337512820959091, -0.04433288052678108, -0.0082829175516963, 0.2567574977874756, 0.252663791179657, -0.2179291546344757, 0.22174608707427979, 0.08132226765155792, -0.3090738356113434, -0.146957129240036, 0.23607680201530457, 0.20998115837574005, -0.16062308847904205, -0.05650761350989342, -0.016277125105261803, -0.04726988449692726, -0.09118612110614777, 0.16558201611042023, 0.05074193701148033, 0.17104175686836243, -0.15068188309669495, 0.014733339659869671, -0.14937753975391388, -0.11916764080524445, 0.155484139919281, 0.023754417896270752, 0.044625118374824524, -0.08206520229578018, 0.08913017064332962, 0.024312175810337067, 0.0009367846651002765, 0.005661738105118275, 0.05393126606941223, 0.10898363590240479, -0.016410553827881813, 0.012223027646541595, 0.025656580924987793, -0.012462892569601536, 0.03689789026975632, 0.07332020998001099, -9.566166409058496e-05, 0.09017180651426315, 0.08653061091899872, -0.01180171687155962, -0.0066548800095915794, -0.0519317202270031, 0.021967511624097824, 0.06129832938313484, 0.11811657249927521, -0.028063487261533737, -0.04511594772338867, 0.09459544718265533, 0.14585231244564056, -0.02967067062854767]     | minishlab/potion-base-2M |
|   9263  |      0      |       0        |  J_1_5  |       text       | This 3-word term once referred to a vessel for boiling the catch at river picnics; today, "fine" or not, it means a hot mess |    [-0.3550836741924286, 0.06608792394399643, 0.023458722978830338, -0.061450425535440445, -0.07730291038751602, 0.12291523814201355, 0.16751834750175476, -0.11952350288629532, -0.13376230001449585, -0.05673300474882126, -0.07803244888782501, -0.04248199239373207, 0.2165815681219101, 0.1169511005282402, 0.383367121219635, -0.07782506942749023, -0.06223473325371742, 0.05786389485001564, 0.10757838934659958, -0.13895876705646515, 0.11291150748729706, 0.009983167052268982, -0.08942312002182007, 0.13734114170074463, 0.008397893980145454, -0.016092874109745026, -0.1125837117433548, -0.185232475399971, 0.039634693413972855, 0.09495417028665543, 0.02738785929977894, 0.12117122858762741, 0.14466777443885803, -0.18421874940395355, 0.06152810528874397, -0.04703858867287636, 0.10452709347009659, 0.017469581216573715, 0.04854315519332886, 0.21831735968589783, -0.041778866201639175, -0.16834385693073273, -0.0816531777381897, 0.025908716022968292, -0.007683940697461367, 0.21204586327075958, 0.043650854378938675, -0.11123469471931458, 0.08714856952428818, -0.018136240541934967, -0.02704482339322567, 0.08157678693532944, -0.002712433459237218, -0.09302744269371033, 0.03849758207798004, -0.08402269333600998, 0.09060119092464447, -0.21089868247509003, 0.12050377577543259, 0.042544715106487274, 0.014834921807050705, -0.14319470524787903, -0.07657407969236374, -0.24711750447750092]    | minishlab/potion-base-2M |

In [3]:
%%sql embeddings_frame <<
SELECT
    c.game_id,
    c.clue_id,
    c.text AS clue_text,
    c.correct_response AS answer_text,
    et.embedding AS clue_embedding,
    ea.embedding AS answer_embedding
FROM clues c
LEFT JOIN embeddings et
    ON  c.game_id = et.game_id
    AND c.round_index = et.round_index
    AND c.category_index = et.category_index
    AND c.clue_id = et.clue_id
    AND et.field = 'text'
LEFT JOIN embeddings ea
    ON  c.game_id = ea.game_id
    AND c.round_index = ea.round_index
    AND c.category_index = ea.category_index
    AND c.clue_id = ea.clue_id
    AND ea.field = 'correct_response'
# WHERE c.correct_response = 'Abraham Lincoln'

Running query in 'duckdb'

In [4]:
embeddings_df = embeddings_frame.PolarsDataFrame()
embeddings_df

shape: (296_438, 6)
┌─────────┬─────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ game_id ┆ clue_id ┆ clue_text         ┆ answer_text       ┆ clue_embedding    ┆ answer_embedding │
│ ---     ┆ ---     ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ i32     ┆ str     ┆ str               ┆ str               ┆ list[f32]         ┆ list[f32]        │
╞═════════╪═════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 9263    ┆ J_1_1   ┆ It's something of ┆ a hill of beans   ┆ [-0.174464,       ┆ [0.154049,       │
│         ┆         ┆ little impor…     ┆                   ┆ -0.016353, …      ┆ 0.022866, …      │
│         ┆         ┆                   ┆                   ┆ 0.124…            ┆ -0.0447…         │
│ 9263    ┆ J_1_2   ┆ In a 1785 poem    ┆ variety           ┆ [-0.161619,       ┆ [0.200613,       │
│         ┆         ┆ William Cowper …  ┆                   ┆ -0.252925, …      ┆ 0.131443, …      │
│         ┆         ┆                   ┆                   ┆ 0.170…            ┆ 0.02995…         │
│ 9263    ┆ J_1_3   ┆ At the dinner     ┆ a hot potato      ┆ [-0.411537,       ┆ [-0.031174,      │
│         ┆         ┆ table, it can be… ┆                   ┆ 0.176504, …       ┆ -0.248948, …     │
│         ┆         ┆                   ┆                   ┆ -0.043…           ┆ 0.041…           │
│ 9263    ┆ J_1_4   ┆ TV's              ┆ take candy from a ┆ [-0.371283,       ┆ [-0.050533,      │
│         ┆         ┆ "MythBusters"     ┆ baby              ┆ 0.15297, …        ┆ -0.198977, …     │
│         ┆         ┆ once tested…      ┆                   ┆ -0.0708…          ┆ -0.02…           │
│ 9263    ┆ J_1_5   ┆ This 3-word term  ┆ kettle of fish    ┆ [-0.355084,       ┆ [0.087339,       │
│         ┆         ┆ once referred…    ┆                   ┆ 0.066088, …       ┆ -0.182288, …     │
│         ┆         ┆                   ┆                   ┆ -0.247…           ┆ -0.016…          │
│ …       ┆ …       ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ 4792    ┆ DJ_2_2  ┆ Examples of this  ┆ an inclined plane ┆ [0.015896,        ┆ [-0.159539,      │
│         ┆         ┆ 2-word slopin…    ┆                   ┆ 0.314941, …       ┆ -0.056347, …     │
│         ┆         ┆                   ┆                   ┆ -0.0992…          ┆ -0.01…           │
│ 4792    ┆ DJ_2_3  ┆ The exosphere,    ┆ helium            ┆ [0.098982,        ┆ [0.13848,        │
│         ┆         ┆ the edge of the…  ┆                   ┆ -0.077989, …      ┆ -0.127425, …     │
│         ┆         ┆                   ┆                   ┆ -0.003…           ┆ 0.13374…         │
│ 4792    ┆ DJ_3_1  ┆ This Minnesota    ┆ the Mayo Clinic   ┆ [0.200365,        ┆ [0.191855,       │
│         ┆         ┆ facility serves…  ┆                   ┆ 0.480962, …       ┆ -0.006696, …     │
│         ┆         ┆                   ┆                   ┆ 0.00598…          ┆ 0.1495…          │
│ 4792    ┆ DJ_3_2  ┆ Since this        ┆ St. Jude's        ┆ [0.129078,        ┆ [0.049408,       │
│         ┆         ┆ pediatric         ┆                   ┆ 0.197841, …       ┆ -0.133544, …     │
│         ┆         ┆ hospital …        ┆                   ┆ 0.08666…          ┆ -0.068…          │
│ 4792    ┆ DJ_3_3  ┆ Founded in 1973,  ┆ the Transplant    ┆ [0.270984,        ┆ [0.135739,       │
│         ┆         ┆ this center a…    ┆ Center            ┆ 0.196703, …       ┆ 0.307399, …      │
│         ┆         ┆                   ┆                   ┆ 0.05039…          ┆ 0.12418…         │
└─────────┴─────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [5]:
game_id = 5811
clue_id = "J_1_1"

In [6]:
%%sql closest_answers <<
WITH query AS (
    SELECT embedding
    FROM embeddings
    WHERE game_id = {{game_id}} AND clue_id = '{{clue_id}}' AND field = 'text'
    LIMIT 1
)
SELECT
    e.game_id,
    e.clue_id,
    e.source_text AS answer_text,
    list_cosine_similarity(q.embedding, e.embedding) AS similarity
FROM embeddings e, query q
WHERE e.field = 'correct_response'
ORDER BY similarity DESC
LIMIT 10

Running query in 'duckdb'

In [7]:
%%sql clue_info <<
SELECT text AS clue_text, correct_response AS correct_answer
FROM clues
WHERE game_id = {{game_id}} AND clue_id = '{{clue_id}}'
LIMIT 1

Running query in 'duckdb'

In [8]:
info = clue_info.PolarsDataFrame()
print(f"Clue:   {info['clue_text'][0]}")
print(f"Answer: {info['correct_answer'][0]}\n")

closest_answers_df = closest_answers.PolarsDataFrame()
closest_answers_df

Clue:   "A mythological creature is suspected in a death. Ruben Blades, Gillian Anderson, David Duchovny"
Answer: The X-Files

shape: (10, 4)
┌─────────┬─────────┬─────────────────────────────────┬────────────┐
│ game_id ┆ clue_id ┆ answer_text                     ┆ similarity │
│ ---     ┆ ---     ┆ ---                             ┆ ---        │
│ i32     ┆ str     ┆ str                             ┆ f32        │
╞═════════╪═════════╪═════════════════════════════════╪════════════╡
│ 3375    ┆ J_2_3   ┆ David Duchovny                  ┆ 0.653141   │
│ 4029    ┆ DJ_3_1  ┆ David Duchovny                  ┆ 0.653141   │
│ 3347    ┆ J_2_2   ┆ David Duchovny                  ┆ 0.653141   │
│ 4394    ┆ DJ_5_2  ┆ David Duchovny                  ┆ 0.653141   │
│ 3629    ┆ DJ_2_1  ┆ David Duchovny                  ┆ 0.653141   │
│ 8767    ┆ J_4_2   ┆ David Duchovny                  ┆ 0.653141   │
│ 8881    ┆ DJ_5_1  ┆ Duchovny                        ┆ 0.588136   │
│ 9058    ┆ DJ_6_2  ┆ mythology                       ┆ 0.562291   │
│ 3295    ┆ DJ_2_2  ┆ Eddie Money is the root of all… ┆ 0.556961   │
│ 3996    ┆ J_3_5   ┆ a pagan                         ┆ 0.528406   │
└─────────┴─────────┴─────────────────────────────────┴────────────┘

In [13]:
from jt3 import nearest_to_centroid

result = nearest_to_centroid(["Abraham Lincoln", "sumo"], 
                             exclude_radius=.8,
                             con=conn,
                             model_name="minishlab/potion-base-2M")
result

shape: (10, 2)
┌─────────────────────────────────┬────────────┐
│ answer_text                     ┆ similarity │
│ ---                             ┆ ---        │
│ str                             ┆ f32        │
╞═════════════════════════════════╪════════════╡
│ Abraham and Isaac               ┆ 0.588104   │
│ Abrahamic                       ┆ 0.553434   │
│ Lincoln in the Bardo            ┆ 0.550938   │
│ Al-Shabaab                      ┆ 0.536127   │
│ what John Wilkes Booth said wh… ┆ 0.534756   │
│ Shinzo Abe                      ┆ 0.531459   │
│ (Shinzo) Abe                    ┆ 0.531132   │
│ Abraham Lincoln: Vampire Hunte… ┆ 0.523331   │
│ (David) Axelrod                 ┆ 0.515635   │
│ aBrachiosaurus                  ┆ 0.512693   │
└─────────────────────────────────┴────────────┘

[('minishlab/potion-base-2M',)]